# Generated by Django 4.2.9 on 2026-03-11 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_investment', models.DecimalField(decimal_places=2, help_text='Investment in BDT', max_digits=12)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10)),
                ('feasibility_score', models.PositiveIntegerField(default=0, help_text='Score 0-100')),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100)),
                ('scenario_description', models.TextField(blank=True)),
                ('projected_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('projected_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('projected_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('projected_roi', models.DecimalField(decimal_places=2, help_text='ROI percentage', max_digits=5)),
                ('risk_assessment', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simulation.businessidea')),
            ],
            options={
                'verbose_name_plural': 'Simulation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
